CarPartImageClassification/Models/Image.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CarPartImageClassification.Models
{
    public enum Classificacao
    {
        [Display(Name = "Front Light")]
        FrontLight,
        [Display(Name = "Back Light")]
        BackLight,
        [Display(Name = "Fog Light")]
        FogLight,
        [Display(Name = "Steering Wheel")]
        SteeringWheel,
        [Display(Name = "Center Console")]
        Console,
        [Display(Name = "Instrument Panel")]
        InstrumentPanel,
        [Display(Name = "Speedometer")]
        Speedometer,
        [Display(Name = "Gear Handle")]
        GearHandle,
        [Display(Name = "Grill")]
        Grill
    }


    public class Image
    {
        [Key]
        [Required]  
        public int Id { get; set; }

        /**
         * URL of the image.
         */
        [Required]
        public string Url { get; set; }

        /**
         * Image location in the filesystem.
         */
        [Required]
        public string ImageLocation { get; set; }

        /**
         * Classification of the image.
         */
        [Required]
        [Display(Name = "Classificação")]
        public Classificacao Classification { get; set; }

        /**
         * Y coordinate of the top border of the bounding box.
         */
        public int? BoundingBoxTop { get; set; }

        /**
         * Y coordinate of the bottom border of the bounding box.
         */
        public int? BoundingBoxBottom { get; set; }

        /**
         * X coordinate of the left border of the bounding box.
         */
        public int? BoundingBoxLeft { get; set; }

        /**
         * X coordinate of the right border of the bounding box.
         */
        public int? BoundingBoxRight { get; set; }

        /**
         * Confirmation if the given bounding box is correct. 
         */
        [Display(Name = "Bounding Box Correta")]
        public bool? BoundingBoxIsCorrect { get; set; }

        /**
         * HITs associated with the image.
         */
        public List<Image_HIT> RelationHIT { get; set; }
    }
}

CarPartImageClassification/Controllers/HITsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CarPartImageClassification.Data;
using CarPartImageClassification.Models;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using Amazon.MTurk;
using Amazon.MTurk.Model;
using CarPartImageClassification.ViewModels;
using System.Collections.Generic;
using System.Xml.Linq;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using System.Drawing;
using Amazon.S3;
using Amazon;
using Amazon.S3.Transfer;

namespace CarPartImageClassification.Controllers
{
    public class HITsController : Controller
    {
        private readonly CarPartImageClassificationContext _context;
        private readonly AmazonMTurkClient _mturkClient;
        private readonly IAmazonS3 _s3Client;
        private readonly IWebHostEnvironment _he;
        private readonly string _bucketName = "boundingboximages";
        private static readonly string URL = "https://mturk-requester-sandbox.us-east-1.amazonaws.com";

        public HITsController(CarPartImageClassificationContext context, IOptions<AWSAuth> awsAuth, IWebHostEnvironment he)
        {
            _context = context;
            _he = he;

            AmazonMTurkConfig config = new AmazonMTurkConfig
            {
                ServiceURL = URL
            };

            _mturkClient = new AmazonMTurkClient(
                awsAuth.Value.AccessKeyID,
                awsAuth.Value.SecretKey,
                config
            );

            _s3Client = new AmazonS3Client(
                awsAuth.Value.AccessKeyID, 
                awsAuth.Value.SecretKey, 
                RegionEndpoint.EUWest3
            );
        }

        // GET: HITs/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
                return NotFound();

            var hitResponse = await _mturkClient.GetHITAsync(new GetHITRequest 
            {
                HITId = id
            });

            var imageRelation = await _context.Image_HIT
                .Include(ir => ir.Image)
                .FirstOrDefaultAsync(ir => ir.MTurkID == id);

            if (imageRelation == null)
                return RedirectToAction("Index", "Images");

            return View(new HITViewModel
            {
                HIT = hitResponse.HIT,
                Image = imageRelation.Image,
                TypeHIT = imageRelation.Type
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AcceptAllAssignments(string id)
        {
            if (id == null)
                return NotFound();

            var assignmentsResponse = await _mturkClient.ListAssignmentsForHITAsync(new ListAssignmentsForHITRequest
            {
                HITId = id,
                AssignmentStatuses = new List<string>() { "Submitted" }
            });

            foreach (var assignment in assignmentsResponse.Assignments)
            {
                await _mturkClient.ApproveAssignmentAsync(new ApproveAssignmentRequest
                {
                    AssignmentId = assignment.AssignmentId
                });
            }

            return RedirectToAction("Details", new { id });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AcceptAllHITsAssignments()
        {
            var hits = await _context.Image_HIT.Where(ih => ih.Finished == false).ToListAsync();

            foreach (var hit in hits)
            {
                var assignmentsResponse = await _mturkClient.ListAssignmentsForHITAsync(new ListAssignmentsForHITRequest
                {
                    HITId = hit.MTurkID,
                    AssignmentStatuses = new List<string>() { "Submitted" }
                });

                foreach (var assignment in assignmentsResponse.Assignments)
                {
                    await _mturkClient.ApproveAssignmentAsync(new ApproveAssignmentRequest
                    {
                        AssignmentId = assignment.AssignmentId
                    });
                }
            }

            return RedirectToAction("Index", "Images");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SaveAllHITsResults()
        {
            var hits = await _context.Image_HIT
                .Include(ih => ih.Image)
                .Where(ih => ih.Finished == false)
                .ToListAsync();

            foreach (var hit in hits)
            {
                var hitResponse = await _mturkClient.GetHITAsync(new GetHITRequest
                {
                    HITId = hit.MTurkID
                });

                var assignmentsResponse = await _mturkClient.ListAssignmentsForHITAsync(new ListAssignmentsForHITRequest
                {
                    HITId = hit.MTurkID,
                    AssignmentStatuses = new List<string>() { "Approved" }
                });

                if (assignmentsResponse.Assignments.Count() == 0)
                    continue;

                // Mark the hit as finished if no assignments left
                if (hitResponse.HIT.NumberOfAssignmentsAvailable == 0 && hitResponse.HIT.NumberOfAssignmentsPending == 0)
                {
                    hit.Finished = true;
                    _context.Update(hit);
                }

                if (hit.Type == Models.Type.Creation)
                {
                    List<int> BoundingBoxesTop = new List<int>();
                    List<int> BoundingBoxesBottom = new List<int>();
                    List<int> BoundingBoxesLeft = new List<int>();
                    List<int> BoundingBoxesRight = new List<int>();

                    XNamespace ns = "http://mechanicalturk.amazonaws.com/AWSMechanicalTurkDataSchemas/2005-10-01/QuestionFormAnswers.xsd";
                    foreach (var assignment in assignmentsResponse.Assignments)
                    {
                        var answerXML = XDocument.Parse(assignment.Answer);
                        var answerJSON = answerXML.Descendants(ns + "Answer").First().Element(ns + "FreeText").Value;

                        var answers = JsonConvert.DeserializeObject<List<AnswerJSON>>(answerJSON);

                        var boundingBox = answers.First().AnnotatedResult.BoundingBoxes.First();
                        BoundingBoxesTop.Add(boundingBox.Top);
                        BoundingBoxesBottom.Add(boundingBox.Top + boundingBox.Height);
                        BoundingBoxesLeft.Add(boundingBox.Left);
                        BoundingBoxesRight.Add(boundingBox.Left + boundingBox.Width);
                    }

                    System.Drawing.Image image = System.Drawing.Image.FromFile(Path.Combine(_he.ContentRootPath, "wwwroot/Images/NoBoundingBox/", hit.Image.ImageLocation));

                    // Filter results with high discrepancy
                    int unfilteredAverageTop = Convert.ToInt32(BoundingBoxesTop.Average());
                    int unfilteredAverageBottom = Convert.ToInt32(BoundingBoxesBottom.Average());
                    int unfilteredAverageLeft = Convert.ToInt32(BoundingBoxesLeft.Average());
                    int unfilteredAverageRight = Convert.ToInt32(BoundingBoxesRight.Average());

                    var heightTreshold = image.Height * 0.25;
                    var widthThreshold = image.Width * 0.25;

                    var FilteredBoundingBoxesTop = BoundingBoxesTop.Where(bb => bb <= unfilteredAverageTop + heightTreshold && bb >= unfilteredAverageTop - heightTreshold).ToList();
                    var FilteredBoundingBoxesBottom = BoundingBoxesBottom.Where(bb => bb <= unfilteredAverageBottom + heightTreshold && bb >= unfilteredAverageBottom - heightTreshold).ToList();
                    var FilteredBoundingBoxesLeft = BoundingBoxesLeft.Where(bb => bb <= unfilteredAverageLeft + widthThreshold && bb >= unfilteredAverageLeft - widthThreshold).ToList();
                    var FilteredBoundingBoxesRight = BoundingBoxesRight.Where(bb => bb <= unfilteredAverageRight *+ widthThreshold && bb >= unfilteredAverageRight - widthThreshold).ToList();

                    hit.Image.BoundingBoxTop = Convert.ToInt32(FilteredBoundingBoxesTop.Average());
                    hit.Image.BoundingBoxBottom = Convert.ToInt32(FilteredBoundingBoxesBottom.Average());
                    hit.Image.BoundingBoxLeft = Convert.ToInt32(FilteredBoundingBoxesLeft.Average());
                    hit.Image.BoundingBoxRight = Convert.ToInt32(FilteredBoundingBoxesRight.Average());

                    // Create a new JPG image with the bounding box for the confirmation 2nd phase task
                    using (Graphics g = Graphics.FromImage(image))
                    {
                        Pen pen = new Pen(Brushes.Red)
                        {
                            Width = 8.0F
                        };

                        Point TopLeft = new Point(Convert.ToInt32(hit.Image.BoundingBoxLeft), Convert.ToInt32(hit.Image.BoundingBoxTop));
                        Point TopRight = new Point(Convert.ToInt32(hit.Image.BoundingBoxRight), Convert.ToInt32(hit.Image.BoundingBoxTop));
                        Point BottomLeft = new Point(Convert.ToInt32(hit.Image.BoundingBoxLeft), Convert.ToInt32(hit.Image.BoundingBoxBottom));
                        Point BottomRight = new Point(Convert.ToInt32(hit.Image.BoundingBoxRight), Convert.ToInt32(hit.Image.BoundingBoxBottom));

                        g.DrawLine(pen, TopLeft, TopRight);
                        g.DrawLine(pen, TopRight, BottomRight);
                        g.DrawLine(pen, BottomLeft, BottomRight);
                        g.DrawLine(pen, TopLeft, BottomLeft);
                    }

                    image.Save(Path.Combine(_he.ContentRootPath, "wwwroot\\Images\\WithBoundingBox\\") + hit.Image.Id.ToString() + ".jpg");

CarPartImageClassification/Controllers/ImagesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CarPartImageClassification.Data;
using CarPartImageClassification.Models;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using CarPartImageClassification.ViewModels;

namespace CarPartImageClassification.Controllers
{
    public class ImagesController : Controller
    {
        private readonly CarPartImageClassificationContext _context;
        private readonly IWebHostEnvironment _he;

        public ImagesController(CarPartImageClassificationContext context, IWebHostEnvironment he)
        {
            _context = context;
            _he = he;
        }

        // GET: Images
        public async Task<IActionResult> Index()
        {
            var boundingBoxesAwaitingConfirmation = await _context.Image
                .Include(i => i.RelationHIT)
                .AnyAsync(i => i.RelationHIT.Where(rh => rh.Type == Models.Type.Confirmation && rh.Finished == false).Count() == 0 && i.BoundingBoxLeft != null && i.BoundingBoxIsCorrect == null);
               
            var imagesAwaitingBoundingBoxes = await _context.Image
                .Include(i => i.RelationHIT)
                .AnyAsync(i => i.RelationHIT.Where(rh => rh.Type == Models.Type.Creation && rh.Finished == false).Count() == 0 && i.BoundingBoxLeft == null);

            var imagesAwaitingCreation = !await _context.Image.AnyAsync();

            var hitsInProgress = await _context.Image_HIT
                .AnyAsync(ih => ih.Finished == false);

            return View(new IndexImageViewModel
            {
                Images = await _context.Image.ToListAsync(),
                AwaitingBoundingBox = imagesAwaitingBoundingBoxes,
                AwaitingConfirmation = boundingBoxesAwaitingConfirmation,
                AwaitingCreation = imagesAwaitingCreation,
                HITsInProgress = hitsInProgress
            });
        }

        public async Task<IActionResult> GenerateImages()
        {
            if (await _context.Image.CountAsync() != 0)
                return RedirectToAction(nameof(Index));

            string filePath = Path.Combine(_he.ContentRootPath, "pictures.txt");
            string file = System.IO.File.ReadAllText(filePath);

            string[] imagesData = file.Split("\r\n");
            
            foreach (string imageData in imagesData)
            {
                try
                {
                    string[] imageDataParsed = imageData.Split(" ");

                    var image = new Image
                    {
                        Url = imageDataParsed[0],
                        Classification = imageDataParsed[1] switch
                        {
                            "front_light" => Classificacao.FrontLight,
                            "back_light" => Classificacao.BackLight,
                            "fog_light" => Classificacao.FogLight,
                            "console" => Classificacao.Console,
                            "grill" => Classificacao.Grill,
                            "speedometer" => Classificacao.Speedometer,
                            "instrument_panel" => Classificacao.InstrumentPanel,
                            "gear_handle" => Classificacao.GearHandle,
                            "steering_wheel" => Classificacao.SteeringWheel,
                            _ => throw new NotImplementedException()
                        },
                        ImageLocation = imageDataParsed[2]
                    };

                    _context.Image.Add(image);
                }
                catch (NotImplementedException)
                {
                    continue;
                }           
            }

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        // GET: Images/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var image = await _context.Image
                .Include(i => i.RelationHIT)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (image == null)
            {
                return NotFound();
            }

            return View(new ImageViewModel
            {
                Image = image,
                CreationHITs = image.RelationHIT.Where(rh => rh.Type == Models.Type.Creation).ToList(),
                ConfirmationHITs = image.RelationHIT.Where(rh => rh.Type == Models.Type.Confirmation).ToList()
            });
        }
 
        // GET: Images/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var image = await _context.Image
                .FirstOrDefaultAsync(m => m.Id == id);
            if (image == null)
            {
                return NotFound();
            }

            return View(image);
        }

        // POST: Images/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var image = await _context.Image.FindAsync(id);
            _context.Image.Remove(image);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ImageExists(int id)
        {
            return _context.Image.Any(e => e.Id == id);
        }
    }
}

CarPartImageClassification/Views/Images/Delete.cshtml
@model CarPartImageClassification.Models.Image

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Image</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Url)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Url)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Classification)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Classification)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BoundingBoxTop)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BoundingBoxTop)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BoundingBoxBottom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BoundingBoxBottom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BoundingBoxLeft)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BoundingBoxLeft)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BoundingBoxRight)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BoundingBoxRight)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BoundingBoxIsCorrect)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BoundingBoxIsCorrect)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CarPartImageClassification/Views/Images/Details.cshtml
@model CarPartImageClassification.ViewModels.ImageViewModel

@{
    ViewData["Title"] = "Imagem";
}

<div>
    @if (((Model.Image.BoundingBoxLeft != null && Model.Image.BoundingBoxIsCorrect == null) || Model.Image.BoundingBoxIsCorrect == false) && Model.ConfirmationHITs.Where(h => h.Finished == false).Count() == 0) {
        <form asp-action="CreateBoundingBoxConfirmationHIT" asp-controller="HITs" method="post">
            <input type="hidden" name="id" value="@Model.Image.Id" />
            <input type="submit" class="btn btn-primary" value="Criar HIT de Confirmação" />
        </form>
    } else if (Model.Image.BoundingBoxLeft == null && Model.CreationHITs.Where(h => h.Finished == false).Count() == 0) {
        <form asp-action="CreateCreationHIT" asp-controller="HITs" method="post">
            <input type="hidden" name="id" value="@Model.Image.Id" />
            <input type="submit" class="btn btn-primary" value="Criar HIT de Geração de Bounding Box" />
        </form>
    }
</div>
<div>
    <h4>Imagem</h4>
    <div class="row">
    @if (Model.Image.BoundingBoxIsCorrect == true) {
        <img src="@Model.Image.Url" style="width: 40%;" />
        <img src=@("/Images/WithBoundingBox/" + @Model.Image.Id + ".jpg") style="width: 40%;" />
    } else {
        <img src="@Model.Image.Url" style="width: 40%;" />
    }
    </div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image.BoundingBoxIsCorrect)
        </dt>
        <dd class = "col-sm-10">
        @if (Model.Image.BoundingBoxIsCorrect == true) {
            <text>Sim</text>
        } else if (Model.Image.BoundingBoxIsCorrect == false) {
            <text>Não</text>
        } else {
            <text>À espera de confirmação</text>
        }
        </dd>
    </dl>
</div>
<div class="pt-1">
    <h6 class="pb-1">HITs de Criação de Bounding Box</h6>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.CreationHITs[0].CreationDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CreationHITs[0].Finished)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        @foreach (var item in Model.CreationHITs)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CreationDate)
                </td>
                <td>
                    @if (item.Finished == true) {
                        <text>Sim</text>
                    } else {
                        <text>Não</text>
                    }
                </td>
                <td>
                    <a asp-action="Details" asp-controller="HITs" asp-route-id="@item.MTurkID">Detalhes</a>
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>
<div class="pt-1">
<h6 class="pb-1">HITs de Confirmação de Bounding Box</h6>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ConfirmationHITs[0].CreationDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ConfirmationHITs[0].Finished)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        @foreach (var item in Model.ConfirmationHITs)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CreationDate)
                </td>
                <td>
                    @if (item.Finished == true) {
                        <text>Sim</text>
                    } else {
                        <text>Não</text>
                    }
                </td>
                <td>
                    <a asp-action="Details" asp-controller="HITs" asp-route-id="@item.MTurkID">Detalhes</a>
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>
<div>
    <a asp-action="Index">Voltar</a>
</div>

CarPartImageClassification/Views/Images/Index.cshtml
@model CarPartImageClassification.ViewModels.IndexImageViewModel

@{
    ViewData["Title"] = "Imagens";
}

<div class="row">
    @if (Model.AwaitingCreation) {
        <div class="pr-2">
            <a asp-action="GenerateImages" class="btn btn-primary">Gerar Imagens</a>
        </div>     
    }
    @if (Model.HITsInProgress) {
        <div class="pr-2">
            <form asp-action="SaveAllHITsResults" asp-controller="HITs" method="post">
                <input type="submit" class="btn btn-primary" value="Processar resultados aprovados" />
            </form>
        </div>
        <div class="pr-2">
            <form asp-action="AcceptAllHITsAssignments" asp-controller="HITs" method="post" class="pr-2">
                <input type="submit" class="btn btn-primary" value="Aprovar todas as respostas em espera" />
            </form>
        </div>
    }
    @if (Model.AwaitingBoundingBox) {
        <div class="pr-2">
            <form asp-action="CreateBoundingBoxHITs" asp-controller="HITs" method="post" class="pr-2">
                <input type="submit" class="btn btn-primary" value="Criar HITs de criação de Bounding Box para todas as imagens" />
            </form>
        </div>  
    }
    @if (Model.AwaitingConfirmation) {
        <div class="pr-2">
            <form asp-action="CreateConfirmationHITs" asp-controller="HITs" method="post" class="pr-2">
                <input type="submit" class="btn btn-primary" value="Criar HITs para bounding boxes à espera de confirmação" />
            </form>
        </div>      
    }
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                Imagem
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Images[0].Classification)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Images) {
        <tr>
            <td>
                <img src=@item.Url width="200" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Classification)
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>